package com.decide.forms.logic
unit DynamicValuesRules;

import com.decide.forms.model.*;

rule "es cliente"
    when
        $question: CurrentQuestion(isPageQuestion("principal","esCliente")) from question
        $form: Form(isPageQuestionAnswered("principal", "esCliente"),
                    getPageQuestionAsBoolean("principal", "esCliente") == true) from form
    then
        $form.makeVisiblePageQuestion("principal","numCliente");
        $form.changeDecimalResponseSectionQuestion("principal","credito","interes",1.75);
        
end

rule "no es cliente"
    when
        $question: CurrentQuestion(isPageQuestion("principal","esCliente")) from question
        $form: Form(isPageQuestionAnswered("principal", "esCliente"),
                    getPageQuestionAsBoolean("principal", "esCliente") == false) from form
    then
        $form.makeNotVisiblePageQuestion("principal","numCliente");
        $form.changeDecimalResponseSectionQuestion("principal","credito","interes",2.25);
        
end

rule "log"
    when
        $form: Form() from form
    then
        System.out.println("[RULES] calculated dynamic values for "+$form.getCode());
end
