package com.decide.forms.logic
unit DynamicValues;

global String question;

import com.decide.forms.model.*;

rule "log current question"
    when
        $question: CurrentQuestion(isPageQuestion("principal","esCliente")) from question
        $form: Form(isPageQuestionAnswered("principal", "esCliente",""),getPageQuestionAsBoolean("principal", "esCliente","")) from form
    then
        System.out.println("[RULES] evaluating logic for principal.esCliente");
end

rule "log"
    when
        $form: Form() from form
    then
        System.out.println("[RULES] calculated dynamic values for "+$form.getCode());
end
