package com.decide.forms.layout
unit Pages;

import com.decide.forms.layout.*;

rule "create form structure"
    when
        $layout: /layout
    then
        $layout.createPage("principal","Principal");
        $layout.createSection("credito","Datos del crédito");
        $layout.createQuestion("nombre","Nombre",com.decide.forms.layout.DataType.TEXT,com.decide.forms.layout.RenderType.TEXTBOX);
        $layout.createQuestion("esCliente","Es cliente?",com.decide.forms.layout.DataType.BOOLEAN,com.decide.forms.layout.RenderType.CHECK_HOR);
        $layout.createQuestion("numCliente","Número de cliente",com.decide.forms.layout.DataType.TEXT,com.decide.forms.layout.RenderType.TEXTBOX);
        $layout.createQuestion("importe","Importe solicitado:",com.decide.forms.layout.DataType.DOUBLE,com.decide.forms.layout.RenderType.DOUBLEBOX);
        $layout.createQuestion("interes","Importe solicitado:",com.decide.forms.layout.DataType.DOUBLE,com.decide.forms.layout.RenderType.DOUBLEBOX);
        $layout.createQuestion("total","Importe solicitado:",com.decide.forms.layout.DataType.DOUBLE,com.decide.forms.layout.RenderType.DOUBLEBOX);
        $layout.addQuestionToStructure("principal",null,0,null,0,"nombre",1);
        $layout.addQuestionToStructure("principal",null,0,null,0,"esCliente",2);
        $layout.addQuestionToStructure("principal",null,0,null,0,"numCliente",3);
        $layout.addQuestionToStructure("principal","credito",4,null,0,"importe",1);
        $layout.addQuestionToStructure("principal","credito",4,null,0,"interes",2);
        $layout.addQuestionToStructure("principal","credito",4,null,0,"total",3);

end

rule "log"
    when
        $layout: FormLayout() from layout
    then
        System.out.println("created pages by rule unit com.decide.forms.pages ...");
end
